AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon MSK Cluster for Kafka Streaming Test

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  Subnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
  Subnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
  Subnet3Cidr:
    Type: String
    Default: 10.0.3.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: vpc-eip-dev-uea1-on-kafka-001

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet1Cidr
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: sn-eip-dev-uea1a-on-kafka-001

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet2Cidr
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: sn-eip-dev-uea1b-on-kafka-001

  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref Subnet3Cidr
      AvailabilityZone: us-east-1c
      Tags:
        - Key: Name
          Value: sn-eip-dev-uea1c-on-kafka-001

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MSK cluster
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: nsg-eip-dev-uea1-on-kafka-001

  MskCluster:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: msk-eip-dev-uea1-on-kakfa-001
      KafkaVersion: 3.5.1
      NumberOfBrokerNodes: 3
      BrokerNodeGroupInfo:
        InstanceType: kafka.t3.small
        ClientSubnets:
          - !Ref Subnet1
          - !Ref Subnet2
          - !Ref Subnet3
        SecurityGroups:
          - !Ref SecurityGroup
        StorageInfo:
          EbsStorageInfo:
            VolumeSize: 1
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: alias/aws/kafka
      EnhancedMonitoring: DEFAULT
      Tags:
        - Key: jbl:owner_email
          Value: oscar_negrete@jabil.com
        - Key: jbl:cost_center
          Value: 4123
        - Key: jbl:backup
          Value: no
        - Key: jbl:project_name
          Value: Kafka Streaming POC
        - Key: jbl:support_team_email
          Value: EIP_Support@jabil.com

  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: iamr-eip-dev-uea1-on-kafka-001
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kafka.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: iamp-eip-dev-uea1-on-kafka-001
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kafka-cluster:Connect
                  - kafka-cluster:AlterCluster
                  - kafka-cluster:DescribeCluster
                Resource: arn:aws:kafka:us-east-1:*:cluster/MSKTestCluster/*
              - Effect: Allow
                Action:
                  - kafka-cluster:*Topic*
                  - kafka-cluster:WriteData
                  - kafka-cluster:ReadData
                Resource: arn:aws:kafka:us-east-1:*:topic/MSKTestCluster/*
              - Effect: Allow
                Action:
                  - kafka-cluster:AlterGroup
                  - kafka-cluster:DescribeGroup
                Resource: arn:aws:kafka:us-east-1:*:group/MSKTestCluster/*

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
  Subnet1Id:
    Description: Subnet ID for us-east-1a
    Value: !Ref Subnet1
  Subnet2Id:
    Description: Subnet ID for us-east-1b
    Value: !Ref Subnet2
  Subnet3Id:
    Description: Subnet ID for us-east-1c
    Value: !Ref Subnet3
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref SecurityGroup
  MskClusterArn:
    Description: MSK Cluster ARN
    Value: !GetAtt MskCluster.Arn
  IamRoleArn:
    Description: IAM Role ARN
    Value: !GetAtt IamRole.Arn
