AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon MSK Cluster for Kafka Streaming Test

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: eip-dev-uea1-on-kafka

Resources:
  ## VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub "vpc-${EnvironmentName}-001"

  ## Subnets
  SubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "sn-${EnvironmentName}-az1a-001"

  SubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "sn-${EnvironmentName}-az1b-001"

  SubnetAZ3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "sn-${EnvironmentName}-az1c-001"

  ## Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Kafka traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 9092
          ToPort: 9092
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "nsg-${EnvironmentName}-001"

  ## IAM Role
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: kafka.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref IAMPolicy
      RoleName: !Sub "iamr-${EnvironmentName}-001"

  IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "kafka-cluster:Connect"
              - "kafka-cluster:AlterCluster"
              - "kafka-cluster:DescribeCluster"
            Resource: !Sub "arn:${AWS::Partition}:kafka:${AWS::Region}:${AWS::AccountId}:cluster/msk-${EnvironmentName}-001/*"
          - Effect: Allow
            Action:
              - "kafka-cluster:*Topic*"
              - "kafka-cluster:WriteData"
              - "kafka-cluster:ReadData"
            Resource: !Sub "arn:${AWS::Partition}:kafka:${AWS::Region}:${AWS::AccountId}:topic/msk-${EnvironmentName}-001/*"
          - Effect: Allow
            Action:
              - "kafka-cluster:AlterGroup"
              - "kafka-cluster:DescribeGroup"
            Resource: !Sub "arn:${AWS::Partition}:kafka:${AWS::Region}:${AWS::AccountId}:group/msk-${EnvironmentName}-001/*"

  ## MSK Cluster
  MSKCluster:
    Type: AWS::MSK::Cluster
    Properties:
      ClusterName: !Sub "msk-${EnvironmentName}-001"
      KafkaVersion: "3.5.1"
      NumberOfBrokerNodes: 3
      BrokerNodeGroupInfo:
        ClientSubnets:
          - !Ref SubnetAZ1
          - !Ref SubnetAZ2
          - !Ref SubnetAZ3
        InstanceType: "kafka.t3.small"
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: 1
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: "aws/kafka"
      EnhancedMonitoring: "DEFAULT"
      ConfigurationInfo:
        Arn: "arn:aws:kafka:us-east-1:000000000000:configuration/msk-default-configuration"
        Revision: 1
      OpenMonitoring:
        Prometheus:
          JmxExporter:
            EnabledInBroker: true
          NodeExporter:
            EnabledInBroker: true
      LoggingInfo:
        BrokerLogs:
          CloudWatchLogs:
            Enabled: true
            LogGroup: !Sub "/aws/msk/${EnvironmentName}-001"
      Tags:
        jbl:owner_email: oscar_negrete@jabil.com
        jbl:cost_center: "4123"
        jbl:backup: "no"
        jbl:project_name: "Kafka Streaming POC"
        jbl:support_team_email: EIP_Support@jabil.com

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${EnvironmentName}-vpc"

  Subnets:
    Description: A list of the created subnets
    Value: !Join [",", [!Ref SubnetAZ1, !Ref SubnetAZ2, !Ref SubnetAZ3]]
    Export:
      Name: !Sub "${EnvironmentName}-subnets"

  SecurityGroup:
    Description: Security group for the cluster
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${EnvironmentName}-securitygroup"

  IAMRole:
    Description: IAM role for the cluster
    Value: !Ref IAMRole
    Export:
      Name: !Sub "${EnvironmentName}-iamrole"

  MSKCluster:
    Description: The MSK cluster
    Value: !Ref MSKCluster
    Export:
      Name: !Sub "${EnvironmentName}-mskcluster"
